// MIT

// WARNING: This file has automatically been generated on Thu, 23 Mar 2023 14:08:30 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package openblas

/*
#include "cblas.h"
#include <stdlib.h>
*/
import "C"

const (
	Sequential = 0
	Thread = 1
	OpenMP = 2
)

type Order int32

const (
	Rowmajor Order = C.CblasRowMajor
	Colmajor Order = C.CblasColMajor
)

type Transpose int32

const (
	Notrans     Transpose = C.CblasNoTrans
	Trans       Transpose = C.CblasTrans
	Conjtrans   Transpose = C.CblasConjTrans
	Conjnotrans Transpose = C.CblasConjNoTrans
)

type UpLo int32

const (
	Upper UpLo = C.CblasUpper
	Lower UpLo = C.CblasLower
)

type Diag int32

const (
	NonUnit Diag = C.CblasNonUnit
	Unit    Diag = C.CblasUnit
)

type Side int32

const (
	Left  Side = C.CblasLeft
	Right Side = C.CblasRight
)

type Layout int32

type Bfloat16 uint16